version: "3"
services:
  json-server:
    build:
      context: ""
      dockerfile: "./Dockerfile"
    entrypoint: ["json-server", "--watch", "db.json", "--host", "0.0.0.0"]
    volumes:
      - ./db.json:/home/app/db.json
    ports:
      - "3001:3000"